### ISSUE TITLE
Icon theme "gnome" not found error. Also 404 on the downlords client download.

### ISSUE THREAD

**Issue by douglasg14b** [tatsujb/installFAFscript#9]
This error pops up after running the script, and selecting the steam install directory.

I then get a "preparing supreme commander forged alliance..." steam game-launch dialog that doesn't change. I eventually close this, paste the launch options, then manually launch supcom to generate the proton debug dump.

The window that was installing java then says:

>Please switch to opened FAF client, waiting on user to log in (if it not open yet simply switch to "install & run steam, steamcmd, FA" terminal tab)... -

________________________________________________________

And stays there indefinitely, there is no FAF client open at this time... and there is no terminal tab with that label?

If I try and run a previously ran command:

>konsole -e /bin/bash --rcfile <(echo "cd faf; ./downlords-faf-client; exit 0")

It flashes a window, and shows the `Icon theme "gnome" not found error` in the console.

__________________________________________

Also note that there is no `downlords-faf-client` under the `faf` folder where that command 

Probably because of:

```
--2019-05-04 15:48:09--  https://github.com/FAForever/downlords-faf-client/releases/download/v0.10.4-beta/_dfc_unix_0_10_4-beta.tar.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-04 15:48:10 ERROR 404: Not Found.
```

There is no file with that release on downlords?

**Comment by douglasg14b** [comment]
@tatsujb 

The client link is:

>https://github.com/FAForever/downlords-faf-client/releases/download/v0.10.4-beta/dfc__unix_0_10_4-beta.tar.gz

Not

>https://github.com/FAForever/downlords-faf-client/releases/download/v0.10.4-beta/_dfc_unix_0_10_4-beta.tar.gz

It needs extra underscores

**Comment by tatsujb** [comment]
yeah. just commited a fix for you

**Comment by douglasg14b** [comment]
Should I run the commands to delete stuff before trying to rerun the script? Or should it be fine to rerun by itself?

**Comment by tatsujb** [comment]
well rerunning it will be a good test for the script. I built it to handle that. it should work

**Comment by tatsujb** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1191

**Comment by douglasg14b** [comment]
@tatsujb 

Reran it, gets to teh same spot `Please switch to opened FAF client...` but no faf client is open. It did not seem to try and download downlords client this time.

```
~/Games/FAF$ ./fafinstall.sh 
install ok installed
install ok installed
install ok installed
install ok installed
install ok installed
install ok installed
install ok installedinstall ok installed

all dependencies met :)

steam user name :
douglasg14b
steam password :

waiting for dependencies to be present... 
-
now moving on to installing Downlord's FAF...
Now seeing if Java was already installed by this script...
Java is already installed, moving on


Please switch to opened FAF client, waiting on user to log in (if it not open yet simply switch to "install & run steam, steamcmd, FA" terminal tab)... \Icon theme "gnome" not found.
-
```

**Comment by tatsujb** [comment]
hmm okay I'll look into that. deleting `~/faf/` should do the trick. also choose "No I do have FA installed" then choose "use my install of FA and install FAF" 

did you run FA from steam once already?

**Comment by douglasg14b** [comment]
The options I chose are `No I do have FA installed` -> `use my install of FA and install FAF`. It then will launch forged alliance (I've launched it previously with the args as well). I will then close FA since I don't think it needs to be open (launching is just for generating that proton debug output?).

After deleting the /faf folder it is now downloading the client. The other terminal windows still opens and tries to launch the client immediately (throwing an icon theme error), even if the original terminal window hasn't installed it yet.

After downloading it gets back to the `Please switch to opened FAF client,` section and sits there.

If I manually execute `konsole -e /bin/bash --rcfile <(echo "cd faf; ./downlords-faf-client; exit 0")` it will open the FAF Client. However, no preferences get changed, and the client does not close.

**Comment by douglasg14b** [comment]
If I rerun teh script to prompt it to change the settings, the downloards client crashes with the following exceptions:

```
2019-05-04 16:48:05.537  WARN 1355 --- [JavaFX-Launcher] c.f.c.preferences.PreferencesService     : Preferences file /home/douglas/.faforever/client.prefs could not be read

java.nio.file.NoSuchFileException: /home/douglas/.faforever/client.prefs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215) ~[na:na]
        at java.base/java.nio.file.Files.newByteChannel(Files.java:369) ~[na:na]
        at java.base/java.nio.file.Files.newByteChannel(Files.java:415) ~[na:na]
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[na:na]
        at java.base/java.nio.file.Files.newInputStream(Files.java:154) ~[na:na]
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2830) ~[na:na]
        at com.faforever.client.preferences.PreferencesService.readExistingFile(PreferencesService.java:178) [downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at com.faforever.client.preferences.PreferencesService.afterPropertiesSet(PreferencesService.java:125) [downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at com.faforever.client.FafClientApplication.init(FafClientApplication.java:69) ~[downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824) ~[javafx-graphics-11-linux.jar:na]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) ~[javafx-graphics-11-linux.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

2019-05-04 16:48:05.539  WARN 1355 --- [JavaFX-Launcher] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'featuredModUpdaterConfig' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/config/FeaturedModUpdaterConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'modService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/mod/ModService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafServerAccessorImpl' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafServerAccessorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
2019-05-04 16:48:05.545  INFO 1355 --- [JavaFX-Launcher] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-04 16:48:05.548 ERROR 1355 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'featuredModUpdaterConfig' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/config/FeaturedModUpdaterConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'modService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/mod/ModService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafServerAccessorImpl' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafServerAccessorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:767) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1]
        at com.faforever.client.FafClientApplication.init(FafClientApplication.java:69) [downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824) [javafx-graphics-11-linux.jar:na]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) [javafx-graphics-11-linux.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'modService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/mod/ModService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafServerAccessorImpl' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafServerAccessorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:767) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 20 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafServerAccessorImpl' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafServerAccessorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:767) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 34 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fafServerAccessorImpl' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/remote/FafServerAccessorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:767) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 48 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preferencesService' defined in URL [jar:file:/home/douglas/faf/lib/downlords-faf-client-0.10.4-beta.jar!/com/faforever/client/preferences/PreferencesService.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 62 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.faforever.client.preferences.PreferencesService.migratePreferences(PreferencesService.java:143) ~[downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at com.faforever.client.preferences.PreferencesService.readExistingFile(PreferencesService.java:185) ~[downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at com.faforever.client.preferences.PreferencesService.afterPropertiesSet(PreferencesService.java:125) ~[downlords-faf-client-0.10.4-beta.jar:0.10.4-beta]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 73 common frames omitted
```

**Comment by douglasg14b** [comment]
It seems the script expect `client.prefs` to exist, but it does not yet.

**Comment by douglasg14b** [comment]
Actually it looks like the script might be deleting the client.prefs?

The file exists until I run the install script and the client opens from the install script.

**Comment by tatsujb** [comment]
my script continues when client.prefs exits and contains your login info. at that point it purposefully crashes  FAF so that it may add the settings to FAF then immediately runs it again. 

at that point you're all set but you can do this whole last bit yoursel, it's just telling FAF where FA is installed to and piping the run arguments the run file. like you used to have to do yourself in the previous versions of the script.

**Comment by douglasg14b** [comment]
The client.prefs file is deleted before that crash it seems, before re-launching the client there is no more `client.prefs` file under `./faforever`. 

It regenerates it on launch (since it doesn't exist), I re-enter my credentials, and the settings are blank.

**Comment by douglasg14b** [comment]
Also noticing that there is no `/run` directory under `~/faf/` tehre is a `~/faf/~/` directory that is empty though?

**Comment by tatsujb** [comment]
this is not my use-case that I demo in the video. I cannot account for FAF's behavior in those cases.

you're on manual now, sorry. but as I said your situation is perfectly recoverable.

and indeed as you have seen and as I was about to tell you FAF does indeed regenerate that file on each run regardless.

stop the script (and do not run it again)

you just need to manually set FAF settings now. everything should be functional.

if the script did not get a chance to copy the run file to `~/faf/` that is fine, it should still be in `/tmp/proton_douglasg/`,  copy it yourself to  `~/faf/`

run is a file not a dir and `~/faf/~/` is because of a typo I fixed in the commit I mentioned earlier. you may delete it.

**Comment by douglasg14b** [comment]
I'm here to report bugs, mainly because I tend to be a bug magnet for scripts, not to harass you. It's why it took me this long to run it, as I almost never get to invest less than 3-5h to a "run and done" script of any sort...

I'm a bit confused what you mean by the use case. I'm running the script to install FAF, nothing more, nothing less. My goal here was to provide bugs/errors/edge-cases so you may fix, document, or provide workarounds for them.

If I could request anything it would be writing out a section that includes paste-able property values for the `client.prefs` file, and a section under **known issues** that includes the script portion to perform all steps after the FAF client preferences changes fail, since it's not a trivial amount of work left to do after that point...

_______________________________________________________

Side note, can the script handle the FAF client failure and move on to other steps instead of stopping part-way when that happens?

**Comment by douglasg14b** [comment]
Correction on the above: If it failed to run the `cp -f /tmp/proton_'$real_user'/run ~/faf/ line and everything after* it's not a trivial amount of work left.

Unfortunately my bash and linux command knowledge is very poor...

**Comment by douglasg14b** [comment]
Alright, wen't through the rest and I can launch games...etc but still cannot launch anything that relies on a lua script like 1v1, phantom, murder party....etc :(

Same errors as before `warning: Running "Z:\home\douglas\.faforever\bin\init.lua" failed: cannot read init_faf.lua: No such file or directory`

Do these things work for you?

**Comment by tatsujb** [comment]
it's on and off. it isn't an exact science. question do you have to keep steam open to be able to play faf or can you play it with steam closed?
